# Generated by Django 2.1.7 on 2019-05-01 14:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ci', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('D', 'Despedido'), ('J', 'Jubilado'), ('R', 'Receso')], default='A', max_length=1)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('D', 'Developer'), ('P', 'ProductOwner'), ('S', 'ScrumMaster')], default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'Usuarios',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
